version: "3"
services:
  express_backend:
    container_name: "express_backend"
    build: ./Express_Backend/
    ports:
      - "3001:3001"
    depends_on:
      - postgres_database
    environment:
      - DB_CONN_STRING=${DB_CONN_STRING}
  postgres_database:
    container_name: "lyristrator-postgres"
    image: "postgres:15"
    ports:
    - "5432:5432"
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: GiveLifeBack2Music!
  airflow-webserver:
    image: apache/airflow:2.7.1
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR}
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SP_DC=${SP_DC}
      - OPENAI_TOKEN=${OPENAI_TOKEN}
    ports:
      - "8080:8080"
    entrypoint: 
      - /bin/bash
      - -c
      - |
        pip install --no-cache-dir -r /opt/airflow/dags/requirements.txt && 
        airflow db upgrade &&
        exec airflow webserver
    depends_on:
      - postgres_database
    volumes:
      - ./Airflow/Dags:/opt/airflow/dags
  airflow-scheduler:
    image: apache/airflow:2.7.1
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR}
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SP_DC=${SP_DC}
      - OPENAI_TOKEN=${OPENAI_TOKEN}
    entrypoint: 
      - /bin/bash
      - -c
      - |
        pip install --no-cache-dir -r /opt/airflow/dags/requirements.txt && 
        airflow db upgrade &&
        exec airflow scheduler
    depends_on:
      - postgres_database
    volumes:
      - ./Airflow/Dags:/opt/airflow/dags
  react_ts_app:
    container_name: "react_ts_app"
    build: ./React_Frontend/Lyristrator-Frontend/
    ports:
      - "3000:80"
